/* data.jsx — auto-generated by render.py from discovery.md.
   Edit discovery.md, then re-run:  python3 scripts/render.py
   Do not edit this file by hand. */

const PERSONA = {
  name: "Evgeny",
  location: "",
  epigraph: "",
  interviewedOn: "",
  interviewLength: "",
};

const ROLES = [
  {
    id: "short-term-rental-operations-airbnb-booking-com-hosts",
    label: "Short-Term Rental Operations (Airbnb/Booking.com hosts)",
    shortLabel: "Short-Term",
    sublabel: "",
    angle: 90,
    orbit: 1,
    intensity: "daily",
    goal: "Maximize occupancy, minimize bad guests, reduce operational overhead",
    practice: [
      "Spreadsheets for guest tracking",
      "WhatsApp groups for team coordination",
      "manual Yelp searches for contractors",
      "visual inspection for utility issues",
    ],
    problems: {
      personal: [],
      researched: [
        { text: "Guest screening/vetting is the #1 cited host pain point (Airbnb community, breezeway.io, multiple sources)", source: "Research" },
        { text: "Guests not reading listings = setup mismatch cancellations (systematic, not one-off)", source: "Research" },
        { text: "False guest claims \u2192 listing suspension (a judge criticized Airbnb's host due process in 2026)", source: "Research" },
        { text: "Amenity complaints = 15% of negative reviews (WiFi, appliances, plumbing)", source: "Research" },
        { text: "California 30-day rule: guests staying 30+ days may acquire tenant rights \u2192 eviction required", source: "Research" },
        { text: "60-day notice + relocation assistance (1 month rent) required for stays >1 year in California", source: "Research" },
        { text: "\"Airbnb squatters\" are a documented phenomenon with legal guides being published", source: "Research" },
        { text: "Guesty/Hostaway designed for entire-home rentals, NOT shared-room/bunkbed/hostel-style operations", source: "Research" },
        { text: "Guest screening tools (Superhog \u00a32/property/month + \u00a32.50/booking; Autohost AI-driven; Safely $5.95/night) do background checks but REQUIRE guest cooperation to submit ID \u2014 they don't solve passive cross-platform screening", source: "Research" },
        { text: "NO cross-platform reputation database exists between Airbnb and Booking.com. Airbnb does not expose its ban list via API.", source: "Research" },
        { text: "No tool alerts hosts when a booking is approaching the 30-day tenant-rights threshold", source: "Research" },
        { text: "Utility monitoring is DIY (smart thermostats) \u2014 no STR-specific cost anomaly detection", source: "Research" },
      ],
    },
    narratives: [
      "Guesty partnered with Booking.com (March 2025)",
      "SB 346 in California (Jan 1, 2026) requires Airbnb/VRBO to share host data with local govts",
      "STR regulations tightening across US cities",
    ],
    openQuestions: [],
  },
];

const NETWORK = [
  {
    id: "str-host-friend",
    name: "STR host friend",
    relation: "",
    distance: 1,
    roles: [
      "Runs 2 properties, similar setup (spreadsheet + WhatsApp)",
    ],
    overlapsWith: [],
    note: "Has same exact pain; can confirm or deny problems; honest peer",
  },
  {
    id: "technical-co-founder",
    name: "Technical co-founder",
    relation: "",
    distance: 1,
    roles: [
      "Built memecoin app with Evgeny",
    ],
    overlapsWith: [],
    note: "Can validate crypto/tech ideas; potential builder",
  },
  {
    id: "r-airbnb-hosts-reddit",
    name: "r/airbnb hosts Reddit",
    relation: "",
    distance: 1,
    roles: [
      "Community of STR operators",
    ],
    overlapsWith: [],
    note: "Mass access to STR host pain points; can post and lurk",
  },
  {
    id: "crypto-conference-contacts",
    name: "Crypto conference contacts",
    relation: "",
    distance: 1,
    roles: [
      "Mostly pivoted to AI agents",
    ],
    overlapsWith: [],
    note: "Weak ties; may know what's being built/funded",
  },
  {
    id: "house-admins-x3",
    name: "House admins (x3)",
    relation: "",
    distance: 1,
    roles: [
      "Live in the properties daily",
    ],
    overlapsWith: [],
    note: "Know operational pain intimately; see what breaks",
  },
  {
    id: "philippines-admin",
    name: "Philippines admin",
    relation: "",
    distance: 1,
    roles: [
      "Handles guest comms remotely",
    ],
    overlapsWith: [],
    note: "Knows where guest screening fails; sees Booking.com issues daily",
  },
];

const DISCOVERY_DOC = `═══════════════════════════════════════════════════════════
DISCOVERY DOCUMENT
Version: 1 | Round: 1/3 | Date: 2026-05-22
Saved: ~/problem-finder/discovery.md
═══════════════════════════════════════════════════════════

## FOUNDER PROFILE

### Professional
Current role: Independent — Airbnb operator (3 properties), content creator (YouTube), crypto/startup explorer
Past roles: iOS engineer at Bank of America, iOS engineer at SoFi
Insider knowledge: Fintech systems, how exchanges work, how financial bubbles inflate; mobile engineering depth; economics of short-term rentals
Hidden expertise: Organic distribution — grew Twitter 0→1,200 in crypto niche; drove 200-300K Reddit impressions; knows Telegram as cheap crypto traffic channel; understands why Reddit impressions don't convert to clicks (traffic ≠ intent)
Built or hacked: Memecoin discovery app (built with friend, 1 year, pitched Coinbase + funds, live-streamed trading); Airbnb operation with distributed team managed over WhatsApp + spreadsheet; grew crypto Twitter account from scratch

### Personal identities and life situations
- Parent: No (not mentioned)
- Pet owner: Not mentioned
- Homeowner / Renter: Rents 3 single-family homes, subleases on Airbnb/Booking.com as bunkbed-style short-term rentals
- Caregiver: Not mentioned
- Chronic condition / Health: Managing weight — calorie counting with "Lose It" app, gym 3–4x/week, experimenting with protein snacks, tracking caloric deficit
- Religious/cultural community: Not mentioned
- Immigrant/expat: From Russia → New York → San Francisco; learned to program in the US
- Other: Motorcyclist, cyclist

### Interests, hobbies, communities
- Crypto / memecoin culture (deep participant and observer)
- YouTube content creation (struggling to grow; best traction on Polymarket tutorials)
- Trading (tried, concluded it's gambling)
- Reading crypto news extensively
- Fitness: gym, biking, motorcycling

### Consumer frustrations
- "Lose It" app for calorie tracking (using it — how satisfied?)
- Airbnb host experience (operational pain managing distributed team via WhatsApp)
- YouTube growth — no algorithm traction despite consistent effort
- Coinbase trading experience (concluded trading doesn't work)
- Booking.com: no review/rating system → attracts guests who are blocked on Airbnb

### Problems they're already solving (detailed STR operational pains)
1. GUEST SCREENING FAILURE: Philippines admin lets low-rating guests book; causes in-house fights, rule violations, odor complaints, noise past 10pm curfew
2. BOOKING.COM QUALITY GAP: No cross-platform review system; some guests are secretly Airbnb-blocked, hopping to Booking.com. Americans in housing crisis using STR as de-facto housing.
3. HOUSE RULE ENFORCEMENT CONFLICTS: House admin enforces rules on 12-15 person shared house; short-term guests resent it → conflicts → complaints escalate to Evgeny
4. BED PREPARATION FAILURES: Bed not ready at check-in (admin missed it, or another guest sat on it) → cancellation requests
5. SETUP MISMATCH CANCELLATIONS: Guests don't realize it's a large shared bunkbed house; cancel after arrival; Airbnb sides with guest → full refund + dates hard to rebook
6. LONG-STAY TENANT TRAP (active legal case): California tenant law requires 60-day notice + relocation assistance (1 month rent) for stays >1yr. Guest changed locks. Eviction filed. Risk of unlawful detainer and non-payment during proceedings.
7. UTILITY COST BLINDNESS: Leaks and high consumption (long showers) only visible via bill 1-2 months later. No real-time visibility. Can't identify which guest/admin is causing overuse.
8. PROCUREMENT MANAGEMENT: Amazon subscription for regulars; one-time buys (bedsheets, etc.) require manual attention; house admins WhatsApp requests for supplies
9. MAINTENANCE COORDINATION: Find contractor on Yelp, schedule, wait, assess honesty of diagnosis, decide to proceed. $300-400 just to show up. Time-consuming and trust-uncertain.
10. HOUSE ADMIN BURNOUT: Admin lives on-site 24/7; constant guest drama; complaining to Evgeny about fatigue
11. AIRBNB CALL DELEGATION IMPOSSIBLE: All Airbnb support calls go to account owner (Evgeny). Can't forward to Philippines admin — would need a separate account/listing per property.

### Markets they represent
- Short-term rental operators (multi-property, hostel-style, self-managed with remote team)
- Airbnb/Booking.com dual-platform hosts
- Retail traders — stocks, options, crypto (technical + fundamental analysis; concluded trading is gambling)
- Content creators / YouTubers (small channel, studying what breaks through vs. stalls)
- Crypto/memecoin insiders and observers
- Russian immigrants to the US (New York, then SF)
- Fintech insiders (Bank of America, SoFi — understands how financial systems work structurally)
- iOS engineers (can build product independently)
- Health-conscious calorie trackers
- Gym-goers focused on body composition (caloric deficit, protein optimization)
- Motorcyclists / cyclists
- Solo founders who've shipped and gone to market (memecoin app, food supplement, YouTube)

### Resources and constraints
Technical ability: Can build independently (iOS engineer, has shipped to App Store); prefers web app (faster, cheaper, no App Store restrictions); knows Telegram mini-apps for crypto
Time available: Full-time
Runway/budget: 3–6 months from Airbnb income
Industries to avoid: [None stated — avoided trading as a product category personally]
Scale goal: Wants to build a real company; has tried venture (crypto app pitched to funds); open to both paths
Co-founder: Has a technical friend from crypto app who could join if idea is compelling
Distribution advantage: Twitter growth (0→1,200), Reddit content (200-300K impressions), Telegram (crypto channel), YouTube live streaming

### Network map
| Role | What they do | Score /25 | Why interesting |
|------|-------------|-----------|-----------------|
| STR host friend | Runs 2 properties, similar setup (spreadsheet + WhatsApp) | 20/25 | Has same exact pain; can confirm or deny problems; honest peer |
| Technical co-founder | Built memecoin app with Evgeny | 15/25 | Can validate crypto/tech ideas; potential builder |
| r/airbnb hosts Reddit | Community of STR operators | 18/25 | Mass access to STR host pain points; can post and lurk |
| Crypto conference contacts | Mostly pivoted to AI agents | 8/25 | Weak ties; may know what's being built/funded |
| House admins (x3) | Live in the properties daily | 16/25 | Know operational pain intimately; see what breaks |
| Philippines admin | Handles guest comms remotely | 14/25 | Knows where guest screening fails; sees Booking.com issues daily |

TOP INTERVIEW TARGETS:
1. STR host friend (2 properties) — closest peer, same pain, honest
2. r/airbnb hosts Reddit — post a question, gather signal at scale
3. House admins — what breaks daily that never gets fixed
4. Philippines admin — where does guest screening actually fail?

---

## INDUSTRY LANDSCAPE

### Short-Term Rental Operations (Airbnb/Booking.com hosts)
Goals: Maximize occupancy, minimize bad guests, reduce operational overhead
Economic structure: Revenue = nightly rate × occupancy; costs = rent + utilities + staff + platform fees + maintenance. Thin margins; bad guests = disproportionate losses.
Typical workflows: Guest inquiry → screen → approve → check-in coordination → in-stay issue handling → checkout → clean → review
Tool stack: Airbnb/Booking.com native tools, then mostly spreadsheets + WhatsApp for small operators. Larger operators use Guesty ($30-150/property/month), Hostaway, Lodgify, Hospitable.
Workarounds: Spreadsheets for guest tracking; WhatsApp groups for team coordination; manual Yelp searches for contractors; visual inspection for utility issues
Recent shifts: Guesty partnered with Booking.com (March 2025); SB 346 in California (Jan 1, 2026) requires Airbnb/VRBO to share host data with local govts; STR regulations tightening across US cities
Pain signals (from web research):
  - Guest screening/vetting is the #1 cited host pain point (Airbnb community, breezeway.io, multiple sources)
  - Guests not reading listings = setup mismatch cancellations (systematic, not one-off)
  - False guest claims → listing suspension (a judge criticized Airbnb's host due process in 2026)
  - Amenity complaints = 15% of negative reviews (WiFi, appliances, plumbing)
  - California 30-day rule: guests staying 30+ days may acquire tenant rights → eviction required
  - 60-day notice + relocation assistance (1 month rent) required for stays >1 year in California
  - "Airbnb squatters" are a documented phenomenon with legal guides being published
Incumbent gap:
  - Guesty/Hostaway designed for entire-home rentals, NOT shared-room/bunkbed/hostel-style operations
  - Guest screening tools (Superhog £2/property/month + £2.50/booking; Autohost AI-driven; Safely $5.95/night) do background checks but REQUIRE guest cooperation to submit ID — they don't solve passive cross-platform screening
  - NO cross-platform reputation database exists between Airbnb and Booking.com. Airbnb does not expose its ban list via API.
  - No tool alerts hosts when a booking is approaching the 30-day tenant-rights threshold
  - Utility monitoring is DIY (smart thermostats) — no STR-specific cost anomaly detection

### Crypto / Memecoin (context only — not primary research focus)
Narrative has shifted significantly from memecoins to AI agents. People from the crypto conference circuit are now building AI agent products. Funding is easier in AI. Telegram mini-apps remain a viable crypto distribution channel with cheaper traffic than web.

### Health & Fitness / Calorie Tracking (eliminated)
Market dominated by MyFitnessPal, Lose It, Cronometer. Crowded. No clear founder-market edge beyond being a user.

### YouTube Content Creation (eliminated)
Very crowded. Evgeny is struggling as a participant himself — building tools here would be building for a market he can't escape from.

---

## CANDIDATE PROBLEMS

---

### Problem 1: Cross-Platform STR Guest Reputation Network
Persona: Multi-platform STR hosts (Airbnb + Booking.com), especially those accepting instant-book Booking.com reservations with zero guest history
Exact pain moment: A Booking.com booking comes in. The host has only the guest's name. No review history, no rating. The guest may be Airbnb-banned — there is no way to know. The virtual assistant approves it. The guest causes damage, starts conflicts, or refuses to leave.
Current workaround: Manual spot-check by VA (unreliable); 4-star rating rule on Airbnb only (doesn't apply to Booking.com); spreadsheet notes of past problems
Why workaround fails: Airbnb does not expose its ban list. Booking.com has no review system. A bad guest can hop platforms indefinitely. The only defense is a human judgment call.
Frequency: Every Booking.com reservation
Emotional weight: HIGH — bad guests can cause property damage, guest conflicts, legal proceedings, revenue loss from cancellations and bad reviews
Financial weight: One bad guest = $500-5,000+ in damage, lost bookings, and time
WTP signal: Evgeny — $50-100/month unprompted. Strong signal.

INCUMBENT RESEARCH FINDINGS:
- GuestsBlacklist.com DOES EXIST — founded in Barcelona, community-driven host blacklist. BUT: clearly hasn't achieved critical mass (Evgeny never heard of it; most hosts in the community don't reference it).
- Superhog, Autohost, Safely: exist but require guest opt-in for ID submission — passive cross-platform check is NOT solved.
- Airbnb community threads from 2019 show hosts have wanted this for 6+ years. Demand is chronic and old.
- Facebook removed a host group that "ridiculed guests" — legal risk is real and has caused prior attempts to fail.

WHY PRIOR ATTEMPTS FAILED:
1. Cold-start problem: database only valuable if many hosts contribute — circular dependency
2. Legal risk: defamation, GDPR, fair housing liability scared off attempts
3. Identity matching: guests can create new accounts; "John Smith" on Booking.com ≠ easily matched to Airbnb
4. No distribution: Barcelona-based GuestsBlacklist.com couldn't reach English-language STR host communities at scale

WHY THIS COULD WORK FOR EVGENY:
- Reddit distribution: can reach r/airbnb hosts with 200-300K impressions. Cold-start is a distribution problem; he has solved distribution before.
- Framing: not a "blacklist" (legal liability) but a "host network trust layer" — contributors get access, data stays private within the network
- Technical moat: phone/email hash matching across platforms + PMS integration (auto-check on booking) removes the manual friction that killed prior attempts
- Booking.com-Guesty partnership (March 2025) signals Booking.com is opening up API access — timing may be right

Incumbent risk: MEDIUM — GuestsBlacklist.com exists but is weak. Superhog/Autohost are adjacent but don't solve this. The gap is real.
Opportunity score: 37/50 (preliminary — elevated from prior estimate given WTP signal and weak incumbents)
Legal architecture needed: Host-contributed data with hashed guest identifiers; no public profiles; private network; clear terms around what constitutes a reportable incident.
Status: ACTIVE — #1 priority for validation interviews

---

### Problem 2: STR Operations for Shared-House / Hostel-Style Operators
Persona: Airbnb/Booking.com hosts running shared-room properties (3-10 "beds" per property), 2-5 properties, lean remote team, not professional property managers
Exact pain moment: Every week: supplies run out and the host has to WhatsApp-order them. A bed isn't made. A guest arrives to find no bed. The house admin forwards a complaint via WhatsApp. A utility bill arrives 2 months late and is $400 higher than expected. A contractor quotes $800 for a fix and the host can't tell if it's fair.
Current workaround: WhatsApp group chats + Google Sheets. No alerts, no accountability, no audit trail. Everything runs through the founder's phone.
Why workaround fails: No visibility into what's happening without being pinged. No way to enforce SLAs on bed prep or cleanliness. No cost tracking by property. No maintenance history. Every problem is a reactive fire.
Frequency: Daily touchpoints across all properties
Emotional weight: HIGH — burnout, phone anxiety, inability to be "off"
Financial weight: Utility overruns ($200-400/month undetected), contractor overcharges, bad reviews from preventable failures, lost bookings from cancellations
Incumbent risk: LOW — Guesty/Hostaway are designed for entire-home rentals, not bunkbed/shared-room operations. They charge $30-150/property/month and require professional property manager scale. Evgeny uses spreadsheets because no tool fits.
Opportunity score: 29/50 (preliminary)
Market size concern: How many shared-room STR operators exist? This is a niche. Needs validation.
Anti-pattern check: Evgeny has 3 live properties as beta customers. One peer confirmed with identical setup.
Status: ACTIVE — needs market size validation + interviews

---

### Problem 3: STR Legal/Regulatory Risk Monitor (California focus)
Persona: California STR hosts who allow stays of 29+ days, especially those using Airbnb for medium-term housing
Exact pain moment: A guest books a 90-day stay. Airbnb doesn't warn the host that after 30 days in California, the guest may acquire tenant rights. The guest stays past checkout. The host now needs a lawyer, a 60-day notice, and potentially $1 month's rent in relocation assistance. This takes 3-4 months and costs $5,000+.
Current workaround: None systematic. Hosts find out from lawyers or from getting burned. Airbnb has a help article (buried) warning about monthly stays.
Why workaround fails: Hosts don't read the help article until it's too late. No alert fires at the 29-day mark. No contract template exists that's optimized for this risk.
Frequency: Every medium/long-term booking — and SB 346 (effective Jan 1, 2026) is tightening California STR regulation further
Emotional weight: HIGH — Evgeny is actively in eviction proceedings RIGHT NOW
Financial weight: $5,000-15,000 in legal costs + months of lost rent + property damage risk
Incumbent risk: LOW — no product exists specifically for this. Legal Zoom has generic templates. Lawyers charge $300+/hour.
Opportunity score: 27/50 (preliminary)
Market size concern: California-specific initially. Expansion path to other states with similar laws (NY, WA, OR).
Status: ACTIVE — narrow but painful; may be a feature of Problem 2 rather than standalone

---

### ELIMINATED: Immigrant Navigation Tools
Why eliminated: Evgeny himself noted "people would be asking ChatGPT all of those questions now." ChatGPT/AI assistants are rapidly eating this use case. Established legal services (Boundless, immigration lawyers) serve the high-stakes tier. No clear founder distribution edge beyond personal experience.

### ELIMINATED: Calorie Tracking / Fitness Tools
Why eliminated: MyFitnessPal (150M users), Lose It, Cronometer dominate. Evgeny is a user, not an insider. No distribution edge specific to this market.

### ELIMINATED: YouTube Growth Tools
Why eliminated: Evgeny is struggling in this market himself. Crowded (VidIQ, TubeBuddy). His Polymarket tutorial success is too narrow to generalize.

---

## TREND OVERLAYS
[TBD]

---

## INTERVIEW SCRIPTS

---

### Script 1 — STR Host Peer (2 properties, similar setup)
**How to reach them:** WhatsApp or call. You already know them.
**Goal:** Confirm the Booking.com guest quality problem, get their WTP, understand what they've tried.
**Time:** 20-30 minutes. Be conversational, not an interrogator.

Opening:
> "Hey, I'm exploring an idea and you came to mind immediately because you're the only other person I know running something like what I run. I want to ask you a few questions about the pain of managing these properties — not to pitch you anything, just to understand if my problems are the same as yours. Can I ask you some stuff?"

Questions to ask (pick 5-6, listen hard, follow threads):
1. "Walk me through the last time a guest caused a serious problem at one of your places. What happened?"
2. "How do you handle Booking.com bookings specifically — do you screen them differently from Airbnb?"
3. "Have you ever had a guest you later realized was probably blocked on Airbnb? How did you find out?"
4. "What's your biggest ongoing headache with the properties right now — the thing that keeps coming back?"
5. "Have you ever tried any software for managing the properties beyond spreadsheets? Why or why not?"
6. "If there was a shared list of problem guests that hosts contributed to — and you could check a name or email before accepting — would you use it? What would you pay per month?"
7. "Who else do you know running multi-property STR? Anyone I should talk to?"

What to listen for: Specific dollar amounts, specific incidents with details, unprompted mentions of cross-platform problems, any tools they tried and abandoned, referrals to other hosts.

What NOT to do: Don't pitch your idea. Don't say "I'm building X." Just listen and ask "tell me more."

---

### Script 2 — Reddit Post on r/airbnb hosts
**Goal:** Gather signal from 50-200+ hosts in one post. Do NOT pitch anything.
**Format:** Problem-sharing post, not a product pitch. Reddit hates pitches; it loves authentic complaints.

**Post title options (test one):**
- "How do you screen Booking.com guests? I feel blind every time one books."
- "Anyone else feel like Booking.com sends the guests Airbnb won't take?"
- "Lost $800 to a guest who I later learned was banned on Airbnb — how do you protect yourselves?"

**Post body:**
> "Running 3 properties on both Airbnb and Booking.com. On Airbnb I can at least see ratings and reviews. On Booking.com it's just a name and sometimes an email.
>
> I've had two situations in the last year where a guest caused real damage and drama — and afterwards I suspected (but couldn't confirm) they'd been banned on Airbnb and hopped to Booking.com because there's no review system there.
>
> How do you handle this? Do you screen Booking.com bookings differently? Has anyone tried any tools or systems for tracking problem guests across platforms?
>
> Genuinely trying to figure out if others have solved this or if we're all just accepting it as the cost of doing business on Booking.com."

**What to watch for in comments:**
- Hosts confirming the exact same pain (with specifics = real)
- Anyone mentioning tools they tried (GuestsBlacklist, Superhog, etc.)
- Anyone saying "this isn't actually a problem for me" + why
- Dollar amounts anyone mentions (damage costs, tool costs)
- DMs from hosts who want to talk more

**After posting:** Reply to every comment within 24 hours to keep the thread alive. DM the most detailed responses: "Would you be up for a 15-min call? I'm trying to understand this better."

---

### Script 3 — Your Philippines Admin
**Goal:** Understand where the screening process actually breaks down from the inside.
**Format:** WhatsApp voice note or call. Frame it as wanting to improve his process, not interrogating him.
**Time:** 10-15 minutes.

Opening:
> "Hey, I want to talk to you about how we handle Booking.com bookings — not to criticize anything, I'm trying to improve our system. I think we're missing things that aren't your fault. Can I ask you a few questions?"

Questions:
1. "When a Booking.com booking comes in, walk me through exactly what you do — step by step."
2. "What information do you have about the guest when you approve it? Just the name, or more?"
3. "When you get a Booking.com booking and something feels off — what does that look like? Do you have a way to check anything?"
4. "What's the hardest part of your job right now — the thing that comes up again and again that you don't have a good way to handle?"
5. "If you had a way to look up whether a guest had caused problems at other properties — like a shared list — how often do you think you'd use it?"
6. "What would make your job significantly easier?"

What to listen for: Specific friction in the screening process, any tools he's heard of or tried, what information he wishes he had, signs of burnout or workarounds he's invented himself.

---

## INTERVIEW DATA
[Empty — Round 1]

---

## OPEN QUESTIONS

### Personal profile gaps (ask Evgeny directly)
- Partner/spouse? If yes, what do they do — any problems in their work or life that stood out?
- Pets?
- Part of any Russian/Eastern European immigrant community in SF — online groups, Telegram, meetups?
- Part of any motorcycle communities or clubs?
- What do people in your life actually ask YOU for help with — what are you the go-to person for?
- Is there anything you've figured out (in STR ops, trading, building the app) that someone told you "you should teach or sell that"?
- Last time you searched "is there an app for this" and found nothing — what was it?
- What do you pay for regularly outside STR/crypto that you're genuinely unhappy with?
- Any industries you'd never want to build in (ethical, personal, or practical reasons)?

### Candidate problem gaps (ask Evgeny directly)
- How many Booking.com bookings per month vs. Airbnb, across all 3 properties?
- Looking back at the last 12 months — how much did bad guests actually cost you in total? (damage + time + lost bookings + legal)
- Had you heard of GuestsBlacklist.com before today?
- Do you think other hosts would *contribute* data to a shared reputation network, or just consume? What would motivate them to contribute?
- What would make you distrust the data in a guest reputation network — what would make you think it was garbage or unfair?
- Are you in any Facebook groups for STR hosts, beyond Reddit?
- Any connections at Airbnb or Booking.com from your fintech days?

### Research gaps (to answer via web search or interviews)
- How many active STR hosts globally list on both Airbnb AND Booking.com? (market size for Problem 1)
- What specifically caused GuestsBlacklist.com to stagnate — legal issue, cold-start, or product?
- Does Booking.com's March 2025 Guesty partnership open any API access that could enable cross-platform guest data?
- Are there professional STR host associations (like VRMA) where a reputation network could be seeded?
- What do r/airbnb hosts threads say when hosts ask about cross-platform guest screening?

═══════════════════════════════════════════════════════════
END OF DISCOVERY DOCUMENT v1
Next step: 
  1. Call your STR host peer (Script 1) — this week
  2. Post on r/airbnb hosts (Script 2) — this week
  3. Talk to your Philippines admin (Script 3) — this week
  4. Come back with notes → type /problem-finder
Resume: type /problem-finder in a new session — document loads automatically
═══════════════════════════════════════════════════════════
`;

Object.assign(window, { PERSONA, ROLES, NETWORK, DISCOVERY_DOC });